### PR TITLE
Remove the this from Init

### PR DESCRIPTION
**Pull request by jamesmontemagno**
It no longer exists!

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Actually I think it’s time for a release. This is added on master right now.

**Comment by jonathanpeppers** [comment]
Let me merge #41 and I can put up a prerelease maybe this weekend.

There was a huge change here. Now I’m using the official Xamarin.Android.Glide NuGet and killed my binding project.

**Comment by jamesmontemagno** [comment]
Awesome! <3 this is exciting!

**Comment by jonathanpeppers** [comment]
The update should be live shortly: https://www.nuget.org/packages/glidex.forms/2.0.0-pre1

The empty `Init()` is deprecated now, because it was using `Forms.Context`, which is also deprecated.

File an issue if you find any problems, thanks!

**Pull request closed without merging**
