### PR TITLE
Create EmbbadedImage.xaml

### PR DESCRIPTION
**Pull request by assaab**

### CODE REVIEW

**Review by jonathanpeppers — CHANGES_REQUESTED** [review]
Can you share a screenshot of what you see on the screen?

Did you forgot to include the image?

**Comment by assaab** [comment]
yes i didn't add an image it was not allowing me to upload file?
Second there was nothing on the screen . no image was loaded.

**Comment by jonathanpeppers** [comment]
So you'd commit the image in the sample app, in this PR?

A `.xaml` layout with an image not in the app will not display anything. So I'm confused what we have to fix here?

**Comment by assaab** [comment]
Screenshot 2021-12-03 193714

**Comment by assaab** [comment]
Screenshot 2021-12-03 193638

**Comment by assaab** [comment]
some image was loaded while the other isn't

**Comment by assaab** [comment]
ads

**Comment by assaab** [comment]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows

ImageResourceExtension is a class recommended by Microsoft to return the image source of an Embedderd Resource image.

**Pull request closed without merging**
